/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;
import paneles.*;
/**
 *
 * @author willruiz
 */
public class Comandas extends javax.swing.JPanel {

    /**
     * Creates new form Comandas1
     */
    public Comandas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnEmpezarComanda = new javax.swing.JButton();
        btnVerComanda = new javax.swing.JButton();
        btnModificarComanda = new javax.swing.JButton();
        btnListarComanda = new javax.swing.JButton();
        btnEliminarComanda = new javax.swing.JButton();

        background.setBackground(new java.awt.Color(227, 232, 232));
        background.setPreferredSize(new java.awt.Dimension(750, 430));

        titulo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        titulo.setText("COMANDAS");

        btnEmpezarComanda.setBackground(new java.awt.Color(0, 102, 153));
        btnEmpezarComanda.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnEmpezarComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpezarComanda.setText("Empezar Comanda");
        btnEmpezarComanda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEmpezarComanda.setMaximumSize(new java.awt.Dimension(160, 20));
        btnEmpezarComanda.setMinimumSize(new java.awt.Dimension(160, 20));
        btnEmpezarComanda.setPreferredSize(new java.awt.Dimension(160, 20));
        btnEmpezarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarComandaActionPerformed(evt);
            }
        });

        btnVerComanda.setBackground(new java.awt.Color(0, 102, 153));
        btnVerComanda.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnVerComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnVerComanda.setText("Ver Comanda");
        btnVerComanda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVerComanda.setMaximumSize(new java.awt.Dimension(160, 20));
        btnVerComanda.setMinimumSize(new java.awt.Dimension(160, 20));
        btnVerComanda.setPreferredSize(new java.awt.Dimension(160, 20));
        btnVerComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerComandaActionPerformed(evt);
            }
        });

        btnModificarComanda.setBackground(new java.awt.Color(0, 102, 153));
        btnModificarComanda.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnModificarComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarComanda.setText("Modificar Comanda");
        btnModificarComanda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarComanda.setMaximumSize(new java.awt.Dimension(160, 20));
        btnModificarComanda.setMinimumSize(new java.awt.Dimension(160, 20));
        btnModificarComanda.setPreferredSize(new java.awt.Dimension(160, 20));
        btnModificarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarComandaActionPerformed(evt);
            }
        });

        btnListarComanda.setBackground(new java.awt.Color(0, 102, 153));
        btnListarComanda.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnListarComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnListarComanda.setText("Listar Comandas");
        btnListarComanda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnListarComanda.setMaximumSize(new java.awt.Dimension(160, 20));
        btnListarComanda.setMinimumSize(new java.awt.Dimension(160, 20));
        btnListarComanda.setPreferredSize(new java.awt.Dimension(160, 20));
        btnListarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarComandaActionPerformed(evt);
            }
        });

        btnEliminarComanda.setBackground(new java.awt.Color(0, 102, 153));
        btnEliminarComanda.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnEliminarComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarComanda.setText("Eliminar Comanda");
        btnEliminarComanda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminarComanda.setMaximumSize(new java.awt.Dimension(160, 20));
        btnEliminarComanda.setMinimumSize(new java.awt.Dimension(160, 20));
        btnEliminarComanda.setPreferredSize(new java.awt.Dimension(160, 20));
        btnEliminarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarComandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModificarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVerComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEmpezarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnListarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(titulo)))
                        .addGap(0, 269, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnEmpezarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnModificarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarComandaActionPerformed
        empezarComanda frameEmpezar = new empezarComanda();
        frameEmpezar.setVisible(true);
    }//GEN-LAST:event_btnEmpezarComandaActionPerformed

    private void btnVerComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerComandaActionPerformed
        verComanda frameVerComanda = new verComanda();
        frameVerComanda.setVisible(true);
    }//GEN-LAST:event_btnVerComandaActionPerformed

    private void btnModificarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarComandaActionPerformed
        modificarComanda frameModificarComanda = new modificarComanda();
        frameModificarComanda.setVisible(true);
    }//GEN-LAST:event_btnModificarComandaActionPerformed

    private void btnListarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarComandaActionPerformed
        listarTodasComandas framelistarComandas = new listarTodasComandas();
        framelistarComandas.setVisible(true);
    }//GEN-LAST:event_btnListarComandaActionPerformed

    private void btnEliminarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarComandaActionPerformed
        eliminarComanda frameEliminarComanda = new eliminarComanda();
        frameEliminarComanda.setVisible(true);
    }//GEN-LAST:event_btnEliminarComandaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnEliminarComanda;
    private javax.swing.JButton btnEmpezarComanda;
    private javax.swing.JButton btnListarComanda;
    private javax.swing.JButton btnModificarComanda;
    private javax.swing.JButton btnVerComanda;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
