/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;
import paneles.*;
/**
 *
 * @author willruiz
 */
public class Platos extends javax.swing.JPanel {

    /**
     * Creates new form Platos1
     */
    public Platos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegistrarPlato = new javax.swing.JButton();
        btnEliminarPlato = new javax.swing.JButton();
        btnListarPlato = new javax.swing.JButton();

        background.setBackground(new java.awt.Color(227, 232, 232));
        background.setPreferredSize(new java.awt.Dimension(750, 430));

        titulo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        titulo.setText("PLATOS");

        btnRegistrarPlato.setBackground(new java.awt.Color(0, 102, 153));
        btnRegistrarPlato.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnRegistrarPlato.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPlato.setText("Registrar Plato");
        btnRegistrarPlato.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRegistrarPlato.setMaximumSize(new java.awt.Dimension(160, 20));
        btnRegistrarPlato.setMinimumSize(new java.awt.Dimension(160, 20));
        btnRegistrarPlato.setPreferredSize(new java.awt.Dimension(160, 20));
        btnRegistrarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPlatoActionPerformed(evt);
            }
        });

        btnEliminarPlato.setBackground(new java.awt.Color(0, 102, 153));
        btnEliminarPlato.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnEliminarPlato.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPlato.setText("Eliminar Plato");
        btnEliminarPlato.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminarPlato.setMaximumSize(new java.awt.Dimension(160, 20));
        btnEliminarPlato.setMinimumSize(new java.awt.Dimension(160, 20));
        btnEliminarPlato.setPreferredSize(new java.awt.Dimension(160, 20));
        btnEliminarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPlatoActionPerformed(evt);
            }
        });

        btnListarPlato.setBackground(new java.awt.Color(0, 102, 153));
        btnListarPlato.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnListarPlato.setForeground(new java.awt.Color(255, 255, 255));
        btnListarPlato.setText("Listar Platos");
        btnListarPlato.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnListarPlato.setMaximumSize(new java.awt.Dimension(160, 20));
        btnListarPlato.setMinimumSize(new java.awt.Dimension(160, 20));
        btnListarPlato.setPreferredSize(new java.awt.Dimension(160, 20));
        btnListarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPlatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnListarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRegistrarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(titulo)))
                        .addGap(0, 269, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnRegistrarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPlatoActionPerformed
        registrarPlato frameRegistro = new registrarPlato();
        frameRegistro.setVisible(true);
    }//GEN-LAST:event_btnRegistrarPlatoActionPerformed

    private void btnEliminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPlatoActionPerformed
        eliminarPlato frameEliminar = new eliminarPlato();
        frameEliminar.setVisible(true);
    }//GEN-LAST:event_btnEliminarPlatoActionPerformed

    private void btnListarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPlatoActionPerformed
        listarPlatos frameListar = new listarPlatos();
        frameListar.setVisible(true);
    }//GEN-LAST:event_btnListarPlatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnEliminarPlato;
    private javax.swing.JButton btnListarComanda;
    private javax.swing.JButton btnListarPlato;
    private javax.swing.JButton btnRegistrarPlato;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
