/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package paneles;

import javax.swing.DefaultCellEditor;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import static paneles.empezarComanda.getCodigoComanda;
import sql.crudsql;

/**
 *
 * @author willruiz
 */
public class seleccionarPlatos extends javax.swing.JDialog {

    
    
    public seleccionarPlatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public seleccionarPlatos(){
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        subtituloPanel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcodigoComanda = new javax.swing.JTextField();
        btnCargarDatos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPlatos = new javax.swing.JTable();
        btnAñadirPlatos = new javax.swing.JButton();
        btnComprobarPlatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(227, 232, 232));
        background.setPreferredSize(new java.awt.Dimension(750, 430));

        tituloPanel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        tituloPanel.setText("Seleccionar platos");

        btnVolver.setBackground(new java.awt.Color(0, 102, 153));
        btnVolver.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver.setMaximumSize(new java.awt.Dimension(120, 20));
        btnVolver.setMinimumSize(new java.awt.Dimension(120, 20));
        btnVolver.setPreferredSize(new java.awt.Dimension(120, 20));
        btnVolver.setSize(new java.awt.Dimension(120, 20));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        subtituloPanel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        subtituloPanel.setForeground(new java.awt.Color(153, 153, 153));
        subtituloPanel.setText("Seleccione los platos de la comanda:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("CÓDIGO COMANDA");

        btnCargarDatos.setBackground(new java.awt.Color(0, 102, 153));
        btnCargarDatos.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnCargarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarDatos.setText("Cargar");
        btnCargarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCargarDatos.setMaximumSize(new java.awt.Dimension(120, 20));
        btnCargarDatos.setMinimumSize(new java.awt.Dimension(120, 20));
        btnCargarDatos.setPreferredSize(new java.awt.Dimension(120, 20));
        btnCargarDatos.setSize(new java.awt.Dimension(120, 20));
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        tablaPlatos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tablaPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaPlatos);

        btnAñadirPlatos.setBackground(new java.awt.Color(0, 102, 153));
        btnAñadirPlatos.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAñadirPlatos.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadirPlatos.setText("Añadir Platos");
        btnAñadirPlatos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAñadirPlatos.setMaximumSize(new java.awt.Dimension(120, 20));
        btnAñadirPlatos.setMinimumSize(new java.awt.Dimension(120, 20));
        btnAñadirPlatos.setPreferredSize(new java.awt.Dimension(120, 20));
        btnAñadirPlatos.setSize(new java.awt.Dimension(120, 20));
        btnAñadirPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPlatosActionPerformed(evt);
            }
        });

        btnComprobarPlatos.setBackground(new java.awt.Color(0, 102, 153));
        btnComprobarPlatos.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnComprobarPlatos.setForeground(new java.awt.Color(255, 255, 255));
        btnComprobarPlatos.setText("Comprobar Comanda");
        btnComprobarPlatos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnComprobarPlatos.setMaximumSize(new java.awt.Dimension(120, 20));
        btnComprobarPlatos.setMinimumSize(new java.awt.Dimension(120, 20));
        btnComprobarPlatos.setPreferredSize(new java.awt.Dimension(120, 20));
        btnComprobarPlatos.setSize(new java.awt.Dimension(120, 20));
        btnComprobarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarPlatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(tituloPanel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(subtituloPanel)
                                            .addGroup(backgroundLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(69, 69, 69)
                                                .addComponent(txtcodigoComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 107, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addComponent(btnAñadirPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129)
                                .addComponent(btnComprobarPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloPanel))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtituloPanel)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtcodigoComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAñadirPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprobarPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    crudsql crud = new crudsql();
    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        txtcodigoComanda.setText(getCodigoComanda());
        tablaPlatos.setModel(crud.mostrarPlatosComanda());
        addCheckBox(2,tablaPlatos);
        addEditableTextColumn(3, tablaPlatos);
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void btnAñadirPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPlatosActionPerformed
        for (int i = 0; i < tablaPlatos.getRowCount(); i++) {
        String codigoPlato = "";
        int cantidadPlato = 0;
        String codigoComanda = txtcodigoComanda.getText();

        // Verificamos si la fila está seleccionada y si la columna cantidad tiene un valor
        if (IsSelected2(i, 2, tablaPlatos)) {
            codigoPlato = tablaPlatos.getValueAt(i, 0).toString();
            // Intentamos obtener el valor de la columna cantidad y convertirlo a int
            String cantidadStr = tablaPlatos.getValueAt(i, 3).toString();
            if (!cantidadStr.isEmpty()) {
                try {
                    cantidadPlato = Integer.parseInt(cantidadStr);
                } catch (NumberFormatException e) {
                    // Manejamos el caso en que el valor no es un número válido
                    System.err.println("Error al convertir la cantidad a int: " + e.getMessage());
                    continue; // Saltamos el resto del bucle para esta iteración
                }
            }
        }

        // Solo intentamos insertar si se tienen datos válidos
        if (!codigoPlato.isEmpty() &&!codigoComanda.isEmpty() && cantidadPlato > 0) {
            crud.insertarPlatosComanda(codigoPlato, codigoComanda, cantidadPlato);
        }
    }
    }//GEN-LAST:event_btnAñadirPlatosActionPerformed

    private void btnComprobarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarPlatosActionPerformed
        comprobarComanda frameComanda = new comprobarComanda();
        frameComanda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnComprobarPlatosActionPerformed

     //Método para añadir checkbox en cada columna
    public void addCheckBox(int columna, JTable tabla) {
        TableColumn tablec = tabla.getColumnModel().getColumn(columna);
        tablec.setCellEditor(tabla.getDefaultEditor(Boolean.class));
        tablec.setCellRenderer(tabla.getDefaultRenderer(Boolean.class));
    }

    //Método booleano para comprobar si una fila y columna es seleccionada
    //Le pasamos como parametris el numero de la fila, el numero de la columna, y la tabla
//    public boolean IsSelected(int fila, int columna, JTable tabla) {
//        return tabla.getValueAt(fila, columna) != null;
//    }
    
    public boolean IsSelected2(int fila, int columna, JTable tabla) {
    // Verificamos que la fila y la columna estén dentro de los límites válidos
    if (fila >= 0 && fila < tabla.getRowCount() && columna >= 0 && columna < tabla.getColumnCount()) {
        // Comprobamos si la celda en la posición especificada está seleccionada
        return tabla.getValueAt(fila, columna)!= null;
    } else {
        // Devolvemos false si la fila o la columna están fuera de los límites
        return false;
    }
}
    
 public void addEditableTextColumn(int columna, JTable tabla) {
    TableColumn tableColumn = tabla.getColumnModel().getColumn(columna);
    tableColumn.setCellEditor(new DefaultCellEditor(new JTextField()));
    tableColumn.setCellRenderer(new DefaultTableCellRenderer());
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seleccionarPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seleccionarPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seleccionarPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seleccionarPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                seleccionarPlatos dialog = new seleccionarPlatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAñadirPlatos;
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnComprobarPlatos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel subtituloPanel;
    private javax.swing.JTable tablaPlatos;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JTextField txtcodigoComanda;
    // End of variables declaration//GEN-END:variables
}
